apiVersion: v1
kind: Service
metadata:
  name: usermgmt-v1
  namespace: microservices
  labels:
    app: usermgmt-v1
spec:
  selector:
    app: usermgmt-v1
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-v1
  namespace: microservices
  labels:
    app: usermgmt-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-v1
  template:
    metadata:
      labels:
        app: usermgmt-v1
    spec:
      serviceAccountName: my-microservices-sa1
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
      - name: usermgmt-v1
        image: stacksimplify/kube-usermanagement-microservice:1.0.0
        ports:
        - containerPort: 8095
        env:
          - name: DB_HOSTNAME
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "usermgmt"
          - name: DB_USERNAME
            value: "dbadmin"
          - name: DB_PASSWORD
            value: "dbpassword11"  
          - name: NOTIFICATION_SERVICE_HOST
            value: "notification-v1.microservices.svc.cluster.local"
          - name: NOTIFICATION_SERVICE_PORT
            value: "8096"  
---  
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microservices
spec:
  type: ExternalName
  externalName: usermgmtdb.c7hldelt9xfp.us-east-1.rds.amazonaws.com  
