apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-nodeport-service
  labels:
    app: usermgmt-v1
  namespace: microservices    
spec:
  type: NodePort
  selector:
    app: usermgmt-v1
  ports:
  - port: 8095
    targetPort: 8095
    nodePort: 31231
