apiVersion: v1
kind: Service
metadata:
  name: usermgmt-v1
  namespace: microservices
  labels:
    app: usermgmt-v1
spec:
  selector:
    app: usermgmt-v1
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-v1
  namespace: microservices
  labels:
    app: usermgmt-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-v1
  template:
    metadata:
      labels:
        app: usermgmt-v1
    spec:
      serviceAccountName: my-microservices-sa1
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
        - name: proxyinit
          image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v2
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "8095"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"
            - name: "APPMESH_EGRESS_IGNORED_PORTS"
              value: "22, 3306"              
      containers:
      - name: usermgmt-v1
        image: stacksimplify/kube-usermanagement-microservice:1.0.0
        ports:
        - containerPort: 8095
        env:
          - name: DB_HOSTNAME
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "usermgmt"
          - name: DB_USERNAME
            value: "dbadmin"
          - name: DB_PASSWORD
            value: "dbpassword11"  
          - name: NOTIFICATION_SERVICE_HOST
            value: "notification-v1.microservices.svc.cluster.local"
          - name: NOTIFICATION_SERVICE_PORT
            value: "8096"  
      - name: envoy
        image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.12.3.0-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/microservices-mesh/virtualNode/usermgmt-v1"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "us-east-1"            
---  
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microservices
spec:
  type: ExternalName
  externalName: usermgmtdb.c7hldelt9xfp.us-east-1.rds.amazonaws.com  
