apiVersion: v1
kind: Service
metadata:
  name: nlb-app1-nginx
  labels:
    app: app1-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer # Default - CLB
  selector:
    app: app1-nginx
  ports: 
    - port: 80
      targetPort: 80
