apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-ecr
  labels:
    app: backend-restapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeapp-ecr
  template:
    metadata:
      labels:
        app: kubeapp-ecr
    spec:
      containers:
      - name: kubeapp-ecr
        image: 180789647333.dkr.ecr.us-east-1.amazonaws.com/aws-ecr-kubenginx:1.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapp-ecr-service
  labels:
    app: kubeapp-ecr
spec:
  type: NodePort
  selector:
    app: kubeapp-ecr
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31031
