apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: usermgmt-v1
  namespace: microservices
spec:
  meshName: appmesh
  listeners:
    - portMapping:
        port: 8095
        protocol: http
  serviceDiscovery:
    dns:
      hostName: usermgmt-v1.microservices.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: notification-v1.microservices.svc.cluster.local   