apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo1
  region: us-east-1
fargateProfiles:
  - name: fp-app2-profile
    selectors:
      - namespace: fp-app2
  - name: fp-ums-profile
    selectors:
      - namespace: fp-ums
        labels:
          runon: fargate     